points_calculator/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index')
]

points_calculator/driver_standing/urls.py
from django.urls import path

from . import views

app_name = 'drivers'

urlpatterns = [
    path('<str:series>/', views.drivers_standing, name="standing")
]

points_calculator/entries/urls.py
from django.urls import path

from . import views

app_name = 'entries'

# urlpatterns = [
#     path('', views.new, name="new")
# ]

points_calculator/points_calculator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('standings/', include('standings.urls')),
    path('drivers/', include('driver_standing.urls')),
    path('admin/', admin.site.urls),
]

points_calculator/standings/urls.py
from django.urls import path

from . import views

app_name = 'standing'

urlpatterns = [
    path('team/<str:series>/', views.team_standing, name="team"),
    path('manufacturer/<str:series>/', views.manuf_standing, name="manufacturer"),
    path('new/', views.new_result, name="new")
]

points_calculator/driver_standing/models.py
from django.db import models

# Create your models here.

points_calculator/standings/models.py
from django.db import models


class Standing(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

points_calculator/core/views.py
from django.shortcuts import render


def index(request):
    styling = 'py-2 px-2 rounded-xl bg-red-200 text-lg hover:bg-red-500 flex justify-center'

    return render(request, 'core/index.html', {
        'styling': styling
    })

points_calculator/driver_standing/views.py
from django.shortcuts import render
from flask import jsonify
from .functions.driver_funcs import fetch_driver_points
from Utility.series_buttons import get_series_buttons
from Utility.helpers import getRounds


def drivers_standing(request, series):
    # Use different function as this gets entries, not driver points
    drivers = fetch_driver_points(series)

    buttons = get_series_buttons('drivers', series)
    round_list = getRounds(series)

    # if the value is a tuple, means fetch failed, and we have status code and none value
    if isinstance(drivers, tuple):
        status_code, _ = drivers
        error_message = f"Failed to fetch data. Status code: { status_code }"
        return jsonify({"error": error_message}), status_code

    else:
        return render(request, 'driver_standing/drivers_standing.html', {
            'drivers': drivers,
            'buttons': buttons,
            'round_list': round_list
        })

points_calculator/standings/views.py
from django.shortcuts import render, redirect
from flask import jsonify
import json
import requests

from .functions.csv_converter import csv_to_clean_keys
from .functions.team_points.team_points import team_results_byClass
from .functions.team_points.fetch_team_standing import fetch_team_standings
from .functions.manuf.manuf_points import manuf_results_byClass, manuf_results_list
from .functions.manuf.fetch_manuf_points import fetch_manuf_standings
from Utility.series_buttons import get_series_buttons
from Utility.helpers import getRounds, handle_rounds
from .functions.drivers.driver_funcs import driver_results_byClass, handle_drivers


def team_standing(request, series):
    # fetch all team standing values, sorted as a dict with pro/am as keys and list for team vals, remove rounds not used
    team_standing = handle_rounds(series, fetch_team_standings(series))

    round_list = getRounds(series)

    buttons = get_series_buttons('team', series)

    # if the value is a tuple, means fetch failed, and we have status code and none value
    if isinstance(team_standing, tuple):
        status_code, _ = team_standing
        error_message = f"Failed to fetch data. Status code: { status_code }"
        return jsonify({"error": error_message}), status_code

    else:
        return render(request, 'standing/team_standing.html', {
            'team_standing': team_standing,
            'round_list': round_list,
            'buttons': buttons
        })


def manuf_standing(request, series):
    manuf_standing = handle_rounds(series, fetch_manuf_standings(series))

    round_list = getRounds(series)

    buttons = get_series_buttons('manuf', series)

    # if the value is a tuple, means fetch failed, and we have status code and none value
    if isinstance(team_standing, tuple):
        status_code, _ = team_standing
        error_message = f"Failed to fetch data. Status code: { status_code }"
        return jsonify({"error": error_message}), status_code
    else:
        return render(request, 'standing/manuf_standing.html', {
            'manuf_standing': manuf_standing,
            'round_list': round_list,
            'buttons': buttons
        })


def new_result(request):
    if request.method == 'POST':

        result_num = request.POST.get('result_num', '')
        result_csv = request.FILES['result_csv']

        # Take in CSV file and return array of objects as rows
        # {'Pos': '1', 'PIC': '1', '#': '93', 'Class': 'Pro', 'Points': '25', 'Team': 'Racers Edge Motorsports', 'Vehicle': 'Acura NSX GT3 EVO22', 'Series': 'gtwca', 'Manufacturer': 'Acura'}
        result_arr = csv_to_clean_keys(result_csv)

        series = result_arr[0]['Series']

        # Returns results from CSV rows with drivers added and split if duo
        drivers = handle_drivers(result_arr, series, result_num)

        # sort by class, remove dupes, apply points for highest finishing car per team
        team_results = team_results_byClass(result_arr)
        manuf_results = manuf_results_list(
            result_arr) if series == 'gtwca' or series == 'pgt4a' else manuf_results_byClass(result_arr)
        driver_results = driver_results_byClass(drivers, series)

        r_num = f"R{result_num}"
        data = {
            "manufResults": manuf_results,
            "teamResults": team_results,
            "roundNum": r_num,
            "driverResults": driver_results
        }

        url = f'http://localhost:2020/result/{series}'
        headers = {'Content-Type': 'application/json'}
        json_data = json.dumps(data)

        response = requests.post(url, headers=headers, data=json_data)

        if response.status_code == 200:
            print('POST request successful')
            return redirect("standing:team", series)

        else:
            print(f'Error: {response.status_code}')

    else:
        pass
    return render(request, 'standing/new_result.html')

points_calculator/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset='utf-8'>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="{% static 'dropdown.js'%}"></script>

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{%block title%}{%endblock%} | SRO</title>
    </head>
    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">
                <img 
                    src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/SRO_Motorsports_Group_logo.svg/1200px-SRO_Motorsports_Group_logo.svg.png" 
                    alt="SRO Motorsports"
                    class="object-fit h-10 w-15"
                >
            </a>
            <div class="space-x-6">
                <a href="{% url 'standing:new' %}" class="text-lg font-semibold hover:text-gray-500">New Result</a>
                <a href="{% url 'drivers:standing' 'gtwca' %}" class="text-lg font-semibold hover:text-gray-500">Driver Standing</a>
                <a href="{% url 'standing:manufacturer' 'gtwca' %}" class="text-lg font-semibold hover:text-gray-500">Manufacturer Standing</a>
                <a href="{% url 'standing:team' 'gtwca' %}" class="text-lg font-semibold hover:text-gray-500">Team Standing</a>
            </div>
        </nav>
        <div class="px-6 py-6">
            {%block content%}
            {%endblock%}
        </div>
    </body>
</html>

points_calculator/core/templates/core/index.html
{% extends 'core/base.html' %} 

{% block title %} Welcome {% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl text-center text-3xl">
        SRO Points
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <ul class="space-y-2 flex flex-col">

            <a href="{% url 'standing:new' %}">
                <li class="{{ styling }}"> New Result </li>
            </a>
            
            <a href="{% url 'drivers:standing' 'gtwca' %}">
                <li class="{{ styling }}"> Drivers Standings </li>
            </a>
        
            <a href="{% url 'standing:manufacturer' 'gtwca' %}">
                <li class="{{ styling }}"> Manufacturer Standings </li>
            </a>
        
            <a href="{% url 'standing:team' 'gtwca' %}">
                <li class="{{ styling }}"> Team Standings </li>
            </a>
           
        </ul>
    </div>
{% endblock %}

points_calculator/driver_standing/templates/driver_standing/drivers_standing.html
{% extends 'core/base.html' %}
{% load custom_filters %} 

{% block title %}Drivers Standing{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl text-center">Drivers Standings</h1>

    <div class="inline-flex rounded-md w-full gap-3 center mb-6" role="group">
        {% for series, style in buttons.items %}
            <button type="button" class="{{ style.button }}">
                <a href="{% url 'drivers:standing' series %}" class="{{ style.anchor }}">{{ series|upper }}</a>
            </button>
        {% endfor %}
    </div>

    {% for classification, teams in drivers.items %}
        <div class="bg-gray-200 mb-10 border-2 border-black-600 p-1">
            <table class="w-full text-m text-left">
                
                <caption class="w-full h-1/2 text-white uppercase bg-red-500 font-bold">{{ classification }}</caption>
                <thead class="w-full text-m text-black-700 uppercase bg-gray-200 dark:bg-red-800 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-3 py-1">Pos</th>
                        <th scope="col" class="px-3 py-1">Driver</th>
                        <th scope="col" class="px-3 py-1">Total</th>                      
                        {% for round in round_list %}
                            <th scope="col" class="px-3 py-1">{{ round }}</th>
                        {% endfor %}    
                    </tr>
                </thead>
                <tbody>
                    {% for entry in teams %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <td class="px-6 py-4">{{ forloop.counter }}</td>
                        <td class="whitespace-nowrap">{{ entry.name }}</td>
                        <td class="text-center">{{ entry.total_points }}</td>
                        
                        {% for round_num in entry.points|get_rounds %}
                            <td class="text-center">{{ entry.points|get_value:round_num }}</td>
                        {% endfor %} 
                        
                       
                    </tr>
                    {% endfor %}
                </tbody> 
                
            </table>
        </div>
    {% endfor %}
{% endblock %}

points_calculator/standings/templates/standing/manuf_standing.html
{% extends 'core/base.html' %}
{% load custom_filters %} 

{% block title %}Manufacturer Standing{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl text-center">Manufacturer Standings</h1>

    <div class="inline-flex rounded-md w-full gap-3 center mb-6" role="group">
        {% for series, style in buttons.items %}
            <button type="button" class="{{ style.button }}">
                <a href="{% url 'standing:manufacturer' series %}" class="{{ style.anchor }}">{{ series|upper }}</a>
            </button>
        {% endfor %}
    </div>

    {% for classification, teams in manuf_standing.items %}
        <div class="bg-gray-200 mb-10 border-2 border-black-600 p-1">
            <table class="w-full text-m text-left">
                
                <caption class="w-full h-1/2 text-white uppercase bg-red-500 font-bold">{{ classification }}</caption>
                <thead class="w-full text-m text-black-700 uppercase bg-gray-200 dark:bg-red-800 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-3 py-1">Pos</th>
                        <th scope="col" class="px-3 py-1">Manufacturer</th>
                        <th scope="col" class="px-3 py-1">Total</th>                      
                        {% for round in round_list %}
                            <th scope="col" class="px-3 py-1">{{ round }}</th>
                        {% endfor %}    
                    </tr>
                </thead>
                <tbody>
                    {% for entry in teams %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <td class="px-6 py-4">{{ forloop.counter }}</td>
                        <td class="whitespace-nowrap">{{ entry.name }}</td>
                        <td class="text-center">{{ entry.total_points }}</td>
                        
                        {% for round_num in entry.points|get_rounds %}
                            <td class="text-center">{{ entry.points|get_value:round_num }}</td>
                        {% endfor %} 
                        
                       
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endfor %}

{% endblock %}

points_calculator/standings/templates/standing/new_result.html
{% extends 'core/base.html' %}

{% block title %}New Result{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl text-center font-bold">New Result</h1>

    <form method="POST" action="." enctype="multipart/form-data" class="w-full py-4 px-6 bg-gray-200 flex flex-col">

        {% csrf_token %}

        <div class="flex flex-row justify-around w-full mb-4">

            <div class="flex flex-col w-1/4">
                <label class="text-m">Race Number</label>
                <input type="text" class="w-full" name="result_num">
            </div>           

            <div class="relative flex justify-center items-center gap-5 pt-20">
                <button id="series_button" class="relative flex justify-center items-center bg-white border focus:outline-none shadow text-gray-600 rounded foxus:ring ring-gray-200 group">
                    <p class="px-4">Series</p>
                    <span class="border-l p-2 hover:bg-gray-100">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down" viewBox="0 0 16 16"> <path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 13.293V1.5A.5.5 0 0 1 8 1z"/></svg>
                    </span>
                    <div class="absolute hidden group-focus:block top-full min-w-full w-max bg-white shadow-md mt-1 rounded">
                        <ul class="text-left border rounded">
                            <li class="series-select px-4 py-2 text-gray-800 hover:bg-red-500 hover:text-white border-b">GT World Challenge</li>
                            <li class="series-select px-4 py-2 text-gray-800 hover:bg-red-500 hover:text-white border-b">Pirelli GT4 America</li>
                            <li class="series-select px-4 py-2 text-gray-800 hover:bg-red-500 hover:text-white border-b">GT America</li>
                            <li class="series-select px-4 py-2 text-gray-800 hover:bg-red-500 hover:text-white">TC America</li>
                        </ul>

                    </div>
                </button>
            </div>


            
            <div class="flex flex-col">
                <label class="text-m">Result CSV File</label>
                <input type="file" id="csvFileInput" accept=".csv" name="result_csv">
            </div>
        </div>
        <button type="submit" class="py-4 px-8 text-lg bg-red-500 hover:bg-red-700 rounded-xl text-white self-center mt-4">Submit</button>
    </form>


{% endblock %}

points_calculator/standings/templates/standing/team_standing.html
{% extends 'core/base.html' %}
{% load custom_filters %} 

{% block title %}Team Standing{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl text-center">Team Standings</h1>

    <div class="inline-flex rounded-md w-full gap-3 center mb-6" role="group">
        {% for series, style in buttons.items %}
            <button type="button" class="{{ style.button }}">
                <a href="{% url 'standing:team' series %}" class="{{ style.anchor }}">{{ series|upper }}</a>
            </button>
        {% endfor %}
    </div>

    {% for classification, teams in team_standing.items %}
        <div class="bg-gray-200 mb-10 border-2 border-black-600 p-1">
            <table class="w-full text-m text-left">
                
                <caption class="w-full h-1/2 text-white uppercase bg-red-500 font-bold">{{ classification }}</caption>
                <thead class="w-full text-m text-black-700 uppercase bg-gray-200 dark:bg-red-800 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-3 py-1">Pos</th>
                        <th scope="col" class="px-3 py-1">Team</th>
                        <th scope="col" class="px-3 py-1">Total</th>                      
                        {% for round in round_list %}
                            <th scope="col" class="px-3 py-1">{{ round }}</th>
                        {% endfor %}    
                    </tr>
                </thead>
                <tbody>
                    {% for entry in teams %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <td class="px-6 py-4">{{ forloop.counter }}</td>
                        <td class="whitespace-nowrap">{{ entry.name }}</td>
                        <td class="text-center">{{ entry.total_points }}</td>
                        
                        {% for round_num in entry.points|get_rounds %}
                            <td class="text-center">{{ entry.points|get_value:round_num }}</td>
                        {% endfor %} 
                        
                       
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endfor %}

{% endblock %}